### ISSUE TITLE
not functional

### ISSUE THREAD

**Issue by DarkLord-13** [amylokh/Android-App-Controlled-RC-Car-using-Bluetooth-#1]
tried operating the app on one plus nord 2, it keeps closing after clicking any button.

**Comment by amylokh** [comment]
This is an outdated version of the app. You will need to fix it by yourself. Sorry!

**Comment by DarkLord-13** [comment]
could you make a similar app with the similar instructions, but a bit more
personalized according to my project, I'm open to pay you.
